create_tasks_for_precon_meetings:
  description: Check if I have an invite to Precon
  due: 8
  tag: Precon

create_tasks_for_waterfalls:
  baseline:
    description: Waterfall needs to be baselined
    due: 24
    tag: Waterfall_Baseline
  Finish_b4_Start:
    description: Waterfall Finish is before Waterfall Start'
    due: 24
    tag: Waterfall_Finish
  wrong_ESID:
    description: Waterfall Finish not in same season as EISD
    due: 24
    tag: EISD

create_task_for_final_engineering_with_draft_schedules:
  description: Check with Engineering on when a schedule will be finalized
  due: 1
  tag: TE_draft

create_task_for_released_projects_missing_construnction_ready_date:
  description: Check with Engineering on populating the construction ready date
  due: 2
  tag: Ready_Date

create_task_for_eisd_before_energiztion:
  description: Project Energization is after Estimated In-Service Date
  due: 4
  tag: ESID

create_tasks_for_engineering_activities_start_dates:
  description: Check with Engineering on if Electrical Designs were started
  due: 8
  tag:

create_tasks_for_engineering_activities_start_dates:
  Electrical:
    description: Check with Engineering on if Electrical Designs were started
    due: 5
    tag: EdesignStart

  Physical:
    description: Check with Engineering on if Physical Designs were started
    due: 5
    tag: PdesignStart

  Foundation:
    description: Check with Engineering on if Foundation Designs were started
    due: 5
    tag: FdesignStart
  TE:
     description: Ask Engineering to update the TE schedule
     due: 5
     tag: TEStart

create_tasks_for_engineering_activities_finish_dates:
  Electrical:
    description: Check with Engineering on if Electrical Designs were issued
    due: 2
    tag: EdesignFinish
  Physical:
    description: Check with Engineering on if Physical Designs were issued
    due: 2
    tag: PdesignFinish

  Foundation:
    description: Check with Engineering on if Foundation Designs were issued
    due: 2
    tag: FdesignFinish
  TE:
    description: Ask Engineering to update the TE schedule (Finish Date)
    due: 2
    tag: TEFinish

create_tasks_for_construncction_task_request_approval:
  description: Ask Engineering for update on Construction Task Request Approval
  due: 8
  tag:

create_tasks_for_design_book_issued:
  description: Ask Engineering for update on Design Book Issued
  due: .5
  tag: Design_Book

create_tasks_for_wa:
  description: Waterfall needs to be baselined
  due: 5
  tag: WA

create_task_for_relay_settings:
  start:
    description: Check with Relay Setter on when settings are going to be started
    due: 8
  tag: RelaySettings
  finish:
    description: Check with Relay Setter on when settings are going to be issued
    due: 1


create_task_for_add_wa_to_schedule:
  description: Add PETE ID to query for Schedules
  due: 20
  tag: WAtoADD

create_task_for_missing_tiers:
  description: Project Tier Missing
  due: 25
  tag: tier

create_tasks_toa_outside_waterfalls:
  description: TOA request outside Waterfall dates
  due: 6
  tag: TOA

create_tasks_toa_no_active:
  description: No Active TOA for project
  due: 7
  tag: TOA

create_tasks_construnction_summary_before_construnction_ready:
  description: Construction Summary before Construction Ready
  due: 1.5
  tag: Construnction_Ready

create_tasks_station_design_finish_after_construction_ready_date:
  description: Design Finish after Construction Ready Date
  due: 1.5
  tag: Construnction_Ready

create_tasks_line_design_finish_after_construction_ready_date:
  description: Design Finish after Construction Ready Date
  due: 1.5
  tag: Construnction_Ready

create_tasks_line_design_finish_after_construction_ready_date:
  description: Design Finish after Construction Ready Date (Line)
  due: 1.5
  tag: Construnction_Ready

create_tasks_line_activities_conflict:
  description: TE date conflicts with construction/distict summary
  due: .25
  tag: Conflict

create_tasks_station_activities_conflict:
  description: TE date conflicts with construction/distict summary
  due: .25
  tag: Conflict
